name: 模块发布

on:
  push:
    paths:
      - 'gradle.properties'
    branches:
      - master

jobs:
  build:
    uses: dango2887/ReusableWorkflows/.github/workflows/publish_maven_central_v2.yml@master
    with:
      #      module_paths_v2: '{"module": [":tap:core"]}'
      module_paths_v2: '{"module": [":lib:kit"]}'
    secrets: inherit
